apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    svc: restaurant-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restaurant-service
  labels:
    application: ctb
    svc: restaurant-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0

  template:
    metadata:
      labels:
        svc: restaurant-service
        application: ctb
    spec:
      containers:
        name: restaurant-service
        image: CaterBe/restaurant-service:latest
        imagePullPolicy: Always
        ports:
          containerPort: 8080
          name: httpport
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://localhost/ctb_restaurant_service
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ctb-db-secret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ctb-db-secret
                key: password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.cj.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ctb-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ctb-zookeeper:2181
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---




